services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    networks:
      dmz:
        ipv4_address: {ip_addr}
        #Replace with real internal ip address ^
networks:
  dmz:
    external: true
    name: dmz
