services:
  web:
    build:
      context: app
      dockerfile: Dockerfile # Assuming Dockerfile is in the root directory and 'app' is the context folder
      # If your Dockerfile is in the 'app' directory, use context: ./app
    # target: builder # (You may not need 'target: builder' if you are not using multi-stage builds)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    networks:
      dmz:
        ipv4_address: 10.0.25.200
networks:
  dmz:
    external: true
    name: dmz